import os
import re
from collections import Counter
from pathlib import Path
from threading import Lock

from backend.llm.runtime import select_runtime_config

try:
    from llama_cpp import Llama
except ImportError:  # Keep the feed usable until the optional local-AI runtime is installed.
    Llama = None


ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = Path(
    os.environ.get(
        "VAO2_MODEL_PATH",
        ROOT / "models" / "qwen2.5-1.5b-instruct-q4_k_m.gguf",
    )
).expanduser()
GPU_OFFLOAD_AVAILABLE = bool(
    Llama is not None
    and hasattr(__import__("llama_cpp"), "llama_supports_gpu_offload")
    and __import__("llama_cpp").llama_supports_gpu_offload()
)
RUNTIME = select_runtime_config(gpu_offload=GPU_OFFLOAD_AVAILABLE)
MODEL_CONTEXT = RUNTIME.context
MODEL_BATCH = RUNTIME.batch
MODEL_THREADS = RUNTIME.threads
MODEL_GPU_LAYERS = RUNTIME.gpu_layers
MODEL_MAX_TOKENS = RUNTIME.max_tokens
SUMMARY_PIPELINE_VERSION = "qwen-1.5b-v4"

STOP_WORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "de", "des", "du",
    "en", "est", "et", "for", "from", "in", "is", "it", "la", "le", "les",
    "of", "on", "ou", "pour", "que", "qui", "sur", "that", "the", "to",
    "un", "une", "was", "were", "with",
}

SYSTEM_PROMPT = (
    "You are a news summarization assistant. Respond only in English, "
    "use only the provided information, and do not invent any facts."
)
QUESTION_SYSTEM_PROMPT = (
    "You answer questions about one provided article or video transcript. Use only the "
    "provided excerpts. If the answer is not present, say so clearly. Answer in the same "
    "language as the question and do not invent facts."
)

_model = None
_model_error = None
_model_lock = Lock()
_generation_lock = Lock()


def model_cache_key():
    """Identify summaries generated by the current model and prompt pipeline."""
    try:
        stat = MODEL_PATH.stat()
        model_revision = f"{stat.st_size}:{stat.st_mtime_ns}"
    except OSError:
        model_revision = "missing"
    return f"{MODEL_PATH.name}:{model_revision}:{SUMMARY_PIPELINE_VERSION}"


def _words(text):
    return [
        word
        for word in re.findall(r"[^\W\d_]+", text.lower(), flags=re.UNICODE)
        if len(word) > 2 and word not in STOP_WORDS
    ]


def preselect_sentences(text, budget=700):
    """Select informative sentences before sending a short prompt to the LLM."""
    clean_text = " ".join((text or "").split())
    if len(clean_text) <= budget:
        return clean_text

    sentences = re.split(r"(?<=[.!?])\s+", clean_text)
    frequencies = Counter(_words(clean_text))
    scored = []
    seen = set()

    for index, sentence in enumerate(sentences):
        normalized = sentence.casefold().strip()
        tokens = _words(sentence)
        if normalized in seen or len(tokens) < 4:
            continue
        seen.add(normalized)
        score = sum(frequencies[token] for token in tokens) / len(tokens)
        if index < 3:
            score *= 1.4
        scored.append((score, index, sentence))

    selected = []
    used = 0
    for _, index, sentence in sorted(scored, reverse=True):
        extra = len(sentence) + (1 if selected else 0)
        if used + extra > budget:
            continue
        selected.append((index, sentence))
        used += extra

    if not selected:
        return clean_text[:budget].rsplit(" ", 1)[0]
    return " ".join(sentence for _, sentence in sorted(selected))


def prepare_transcript(text, budget=2600):
    """Keep a coherent opening segment and remove caption-only noise."""
    clean_text = re.sub(r"\[[^\]]{1,40}\]", " ", text or "")
    clean_text = re.sub(r">>+", " ", clean_text)
    clean_text = " ".join(clean_text.split())
    if len(clean_text) <= budget:
        return clean_text

    excerpt = clean_text[:budget]
    last_boundary = max(excerpt.rfind(". "), excerpt.rfind("! "), excerpt.rfind("? "))
    if last_boundary >= int(budget * 0.75):
        excerpt = excerpt[: last_boundary + 1]
    else:
        excerpt = excerpt.rsplit(" ", 1)[0]
    return excerpt


def _load_model():
    """Load the GGUF model once in the FastAPI process."""
    global _model, _model_error

    if _model is not None:
        return _model
    if Llama is None:
        _model_error = "llama-cpp-python is not installed"
        return None
    if not MODEL_PATH.is_file():
        _model_error = f"Model not found: {MODEL_PATH}"
        return None

    with _model_lock:
        if _model is not None:
            return _model
        try:
            _model = Llama(
                model_path=str(MODEL_PATH),
                n_ctx=MODEL_CONTEXT,
                n_batch=min(MODEL_BATCH, MODEL_CONTEXT),
                n_threads=MODEL_THREADS,
                n_threads_batch=MODEL_THREADS,
                n_gpu_layers=MODEL_GPU_LAYERS,
                verbose=False,
            )
            _model_error = None
        except (OSError, RuntimeError, ValueError) as error:
            _model_error = str(error)
            return None

    return _model


def status():
    """Return the availability of the embedded llama.cpp runtime and GGUF model."""
    runtime_installed = Llama is not None
    model_installed = MODEL_PATH.is_file()
    return {
        "available": runtime_installed and model_installed,
        "model": MODEL_PATH.name,
        "backend": "llama.cpp",
        "runtime_installed": runtime_installed,
        "model_installed": model_installed,
        "loaded": _model is not None,
        "runtime": RUNTIME.public_dict(),
        "error": _model_error,
    }


def generate_stream(prompt, json_mode=False, system_prompt=SYSTEM_PROMPT):
    """Yield text as llama.cpp decodes it instead of waiting for completion."""
    model = _load_model()
    if model is None:
        return

    parameters = {
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
        "max_tokens": MODEL_MAX_TOKENS,
        "repeat_penalty": 1.15,
        "stop": ["<|im_end|>", "<|endoftext|>"],
        "stream": True,
    }
    if json_mode:
        parameters["response_format"] = {"type": "json_object"}

    try:
        # A Llama context must not be decoded by multiple FastAPI worker threads at once.
        with _generation_lock:
            response = model.create_chat_completion(**parameters)
            for chunk in response:
                content = chunk["choices"][0].get("delta", {}).get("content", "")
                if content:
                    yield content
    except (KeyError, OSError, RuntimeError, TypeError, ValueError):
        return


def generate(prompt, json_mode=False):
    """Generate a complete response for callers that do not consume a stream."""
    content = "".join(generate_stream(prompt, json_mode=json_mode)).strip()
    return content or None


def short_summary_stream(title, text, content_source=""):
    """Yield ``(text, generated_by_ai)`` chunks for a progressive summary."""
    text = (text or "").strip()
    if text:
        is_transcript = content_source == "transcript"
        selected_text = (
            prepare_transcript(text) if is_transcript else preselect_sentences(text, budget=1200)
        )
        instruction = (
            "Summarize this video transcript in two to four factual sentences and fewer "
            "than 80 words. State the video's main activity, what happens, and the result "
            "only when it is explicitly stated. Ignore speech fillers, sound cues, jokes, "
            "sponsors, and calls to action. Do not guess or invent facts."
            if is_transcript
            else "Summarize this news item in two to four factual sentences and fewer "
            "than 80 words. Do not include information absent from the text."
        )
        generated = False
        for chunk in generate_stream(
            f"{instruction}\n\nTitle: {title}\n\nText: {selected_text}"
        ):
            generated = True
            yield chunk, True
        if generated:
            return

    fallback = preselect_sentences(text or title, budget=360)
    yield fallback, False


def select_question_context(question, text, budget=None):
    """Select overlapping excerpts that best match a question."""
    clean_text = " ".join((text or "").split())
    if not clean_text:
        return ""
    if budget is None:
        available_chars = (MODEL_CONTEXT - MODEL_MAX_TOKENS - 180) * 3
        budget = max(1200, min(3600, available_chars))
    if len(clean_text) <= budget:
        return clean_text

    terms = set(_words(question))
    window_size = min(700, budget)
    step = max(350, window_size - 120)
    windows = []
    for index, start in enumerate(range(0, len(clean_text), step)):
        end = min(len(clean_text), start + window_size)
        if end < len(clean_text):
            boundary = clean_text.find(". ", end, min(len(clean_text), end + 160))
            if boundary != -1 or len(clean_text) - end <= 160:
                end = boundary + 1 if boundary != -1 else len(clean_text)
                start = max(0, end - window_size)
        excerpt = clean_text[start:end]
        if not excerpt:
            continue
        excerpt_terms = _words(excerpt)
        matches = sum(1 for word in excerpt_terms if word in terms)
        score = matches * 10 + (1 if index == 0 else 0)
        windows.append((score, index, excerpt))

    selected = []
    used = 0
    for _, index, excerpt in sorted(windows, key=lambda item: (-item[0], item[1])):
        if used + len(excerpt) > budget:
            continue
        selected.append((index, excerpt))
        used += len(excerpt)
    return "\n\n".join(excerpt for _, excerpt in sorted(selected))


def answer_question_stream(title, question, text, content_source=""):
    """Yield an answer grounded in the most relevant source excerpts."""
    excerpts = select_question_context(question, text)
    if not excerpts:
        yield "The source content is unavailable, so I cannot answer this question."
        return
    source_label = "video transcript" if content_source == "transcript" else "article"
    prompt = (
        f"Source type: {source_label}\nTitle: {title}\n\n"
        f"Relevant source excerpts:\n{excerpts}\n\nQuestion: {question}\n\n"
        "Give a concise, direct answer grounded only in the excerpts."
    )
    generated = False
    for chunk in generate_stream(prompt, system_prompt=QUESTION_SYSTEM_PROMPT):
        generated = True
        yield chunk
    if not generated:
        yield "The local AI is unavailable, so I cannot answer this question."


def _parse_suggested_questions(raw_text):
    """Extract up to three clean question lines from an LLM response."""
    questions = []
    for line in (raw_text or "").splitlines():
        cleaned = re.sub(r"^[\s\-*\d.\)]+", "", line).strip()
        if cleaned and cleaned.endswith("?"):
            questions.append(cleaned)
    return questions[:3]


def _template_questions(clean_title, summary, content_source):
    """Fallback prompts used when the local AI cannot ground questions in the summary."""
    summary_words = _words(summary)
    source_name = "video" if content_source == "transcript" else "article"
    questions = [
        f'What is the main point of the {source_name} about “{clean_title}”?',
        f'Which facts or examples support the claims about “{clean_title}”?',
    ]

    concepts = set(summary_words)
    if concepts & {"risk", "risks", "danger", "dangers", "limitation", "limitations"}:
        questions.append("What risks or limitations are mentioned?")
    elif concepts & {"compare", "compared", "comparison", "versus", "difference", "differences"}:
        questions.append("What differences or trade-offs are highlighted?")
    elif concepts & {"future", "next", "plan", "plans", "expected", "upcoming"}:
        questions.append("What does the source say will happen next?")
    elif content_source == "transcript":
        questions.append("What practical advice or recommendations does the video give?")
    else:
        questions.append(f'What consequences or next steps are described for “{clean_title}”?')
    return questions


def suggest_questions(title, summary, content_source=""):
    """Ask the local AI for three questions grounded in this item's own summary."""
    clean_title = " ".join((title or "this content").split()).strip(" -–—:|")
    if len(clean_title) > 64:
        clean_title = clean_title[:64].rsplit(" ", 1)[0] + "…"

    summary = (summary or "").strip()
    if summary:
        source_label = "video transcript" if content_source == "transcript" else "article"
        prompt = (
            f"Source type: {source_label}\nTitle: {clean_title}\n\nSummary:\n{summary}\n\n"
            "Write exactly three short, specific questions a reader could ask about this "
            "summary. One per line, no numbering, no explanations, each ending with '?'."
        )
        questions = _parse_suggested_questions(generate(prompt))
        if len(questions) == 3:
            return questions

    return _template_questions(clean_title, summary, content_source)


def short_summary(title, text, content_source=""):
    """Return a short English summary and whether llama.cpp generated it."""
    chunks = []
    generated_by_ai = False
    for chunk, generated_by_ai in short_summary_stream(title, text, content_source):
        chunks.append(chunk)
    return "".join(chunks).strip(), generated_by_ai
