import os
import re
from collections import Counter
from pathlib import Path
from threading import Lock

try:
    from llama_cpp import Llama
except ImportError:  # Keep the feed usable until the optional local-AI runtime is installed.
    Llama = None


ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = Path(
    os.environ.get(
        "VAO2_MODEL_PATH",
        ROOT / "models" / "qwen2.5-1.5b-instruct-q4_k_m.gguf",
    )
).expanduser()
MODEL_CONTEXT = int(os.environ.get("VAO2_MODEL_CONTEXT", "1536"))
MODEL_THREADS = int(
    os.environ.get("VAO2_MODEL_THREADS", str(min(4, os.cpu_count() or 4)))
)
MODEL_GPU_LAYERS = int(os.environ.get("VAO2_MODEL_GPU_LAYERS", "0"))
MODEL_MAX_TOKENS = int(os.environ.get("VAO2_MODEL_MAX_TOKENS", "100"))
SUMMARY_PIPELINE_VERSION = "qwen-1.5b-v4"

STOP_WORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "de", "des", "du",
    "en", "est", "et", "for", "from", "in", "is", "it", "la", "le", "les",
    "of", "on", "ou", "pour", "que", "qui", "sur", "that", "the", "to",
    "un", "une", "was", "were", "with",
}

SYSTEM_PROMPT = (
    "You are a news summarization assistant. Respond only in English, "
    "use only the provided information, and do not invent any facts."
)

_model = None
_model_error = None
_model_lock = Lock()
_generation_lock = Lock()


def model_cache_key():
    """Identify summaries generated by the current model and prompt pipeline."""
    try:
        stat = MODEL_PATH.stat()
        model_revision = f"{stat.st_size}:{stat.st_mtime_ns}"
    except OSError:
        model_revision = "missing"
    return f"{MODEL_PATH.name}:{model_revision}:{SUMMARY_PIPELINE_VERSION}"


def _words(text):
    return [
        word
        for word in re.findall(r"[^\W\d_]+", text.lower(), flags=re.UNICODE)
        if len(word) > 2 and word not in STOP_WORDS
    ]


def preselect_sentences(text, budget=700):
    """Select informative sentences before sending a short prompt to the LLM."""
    clean_text = " ".join((text or "").split())
    if len(clean_text) <= budget:
        return clean_text

    sentences = re.split(r"(?<=[.!?])\s+", clean_text)
    frequencies = Counter(_words(clean_text))
    scored = []
    seen = set()

    for index, sentence in enumerate(sentences):
        normalized = sentence.casefold().strip()
        tokens = _words(sentence)
        if normalized in seen or len(tokens) < 4:
            continue
        seen.add(normalized)
        score = sum(frequencies[token] for token in tokens) / len(tokens)
        if index < 3:
            score *= 1.4
        scored.append((score, index, sentence))

    selected = []
    used = 0
    for _, index, sentence in sorted(scored, reverse=True):
        extra = len(sentence) + (1 if selected else 0)
        if used + extra > budget:
            continue
        selected.append((index, sentence))
        used += extra

    if not selected:
        return clean_text[:budget].rsplit(" ", 1)[0]
    return " ".join(sentence for _, sentence in sorted(selected))


def prepare_transcript(text, budget=2600):
    """Keep a coherent opening segment and remove caption-only noise."""
    clean_text = re.sub(r"\[[^\]]{1,40}\]", " ", text or "")
    clean_text = re.sub(r">>+", " ", clean_text)
    clean_text = " ".join(clean_text.split())
    if len(clean_text) <= budget:
        return clean_text

    excerpt = clean_text[:budget]
    last_boundary = max(excerpt.rfind(". "), excerpt.rfind("! "), excerpt.rfind("? "))
    if last_boundary >= int(budget * 0.75):
        excerpt = excerpt[: last_boundary + 1]
    else:
        excerpt = excerpt.rsplit(" ", 1)[0]
    return excerpt


def _load_model():
    """Load the GGUF model once in the FastAPI process."""
    global _model, _model_error

    if _model is not None:
        return _model
    if Llama is None:
        _model_error = "llama-cpp-python is not installed"
        return None
    if not MODEL_PATH.is_file():
        _model_error = f"Model not found: {MODEL_PATH}"
        return None

    with _model_lock:
        if _model is not None:
            return _model
        try:
            _model = Llama(
                model_path=str(MODEL_PATH),
                n_ctx=MODEL_CONTEXT,
                n_batch=min(256, MODEL_CONTEXT),
                n_threads=MODEL_THREADS,
                n_threads_batch=MODEL_THREADS,
                n_gpu_layers=MODEL_GPU_LAYERS,
                verbose=False,
            )
            _model_error = None
        except (OSError, RuntimeError, ValueError) as error:
            _model_error = str(error)
            return None

    return _model


def status():
    """Return the availability of the embedded llama.cpp runtime and GGUF model."""
    runtime_installed = Llama is not None
    model_installed = MODEL_PATH.is_file()
    return {
        "available": runtime_installed and model_installed,
        "model": MODEL_PATH.name,
        "backend": "llama.cpp",
        "runtime_installed": runtime_installed,
        "model_installed": model_installed,
        "loaded": _model is not None,
        "error": _model_error,
    }


def generate(prompt, json_mode=False):
    """Generate text in-process with llama.cpp, or return None when unavailable."""
    model = _load_model()
    if model is None:
        return None

    parameters = {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
        "max_tokens": MODEL_MAX_TOKENS,
        "repeat_penalty": 1.15,
        "stop": ["<|im_end|>", "<|endoftext|>"],
    }
    if json_mode:
        parameters["response_format"] = {"type": "json_object"}

    try:
        # A Llama context must not be decoded by multiple FastAPI worker threads at once.
        with _generation_lock:
            response = model.create_chat_completion(**parameters)
        content = response["choices"][0]["message"]["content"]
        return content.strip() or None
    except (KeyError, OSError, RuntimeError, TypeError, ValueError):
        return None


def short_summary(title, text, content_source=""):
    """Return a short English summary and whether llama.cpp generated it."""
    text = (text or "").strip()
    if text:
        is_transcript = content_source == "transcript"
        selected_text = (
            prepare_transcript(text) if is_transcript else preselect_sentences(text, budget=1200)
        )
        instruction = (
            "Summarize this video transcript in two to four factual sentences and fewer "
            "than 80 words. State the video's main activity, what happens, and the result "
            "only when it is explicitly stated. Ignore speech fillers, sound cues, jokes, "
            "sponsors, and calls to action. Do not guess or invent facts."
            if is_transcript
            else "Summarize this news item in two to four factual sentences and fewer "
            "than 80 words. Do not include information absent from the text."
        )
        summary = generate(
            f"{instruction}\n\n"
            f"Title: {title}\n\nText: {selected_text}"
        )
        if summary:
            return summary, True

    fallback = preselect_sentences(text or title, budget=360)
    return fallback, False
